apiVersion: v1
kind: Pod
metadata:
  name: multi-module-build
  labels:
    app: formation
spec:
  containers:
    - name: jdk
      image: openjdk:17-alpine
      command:
      - cat
      tty: true
