version: '2'
services:
  annuaire:
    build: ./annuaire/
    networks:
     - back
    ports:
     - "1111:1111"
  documentservice:
    build: ./documents-service/
    networks:
     - back
  membersservice:
    build: ./members-service/
    networks:
      - back
  notificationservice:
    build: ./notification-service/
    networks:
      - back
  proxy:
    build: ./proxy/
    networks:
      - front
      - back
    ports:
      - 8081:8081
  angular:
    build: ./angular/
    networks:
      - front
    ports:
      - 80:80

networks:
  back:
  front:
