def dataCenter = '';

pipeline {
   agent none 

    tools {
        maven 'MAVEN3'
        jdk 'JDK11'
    }
    stages {
        stage('Compile et tests') {
            agent any 
            steps {
                echo 'Unit test et packaging'
                sh 'mvn -Dmaven.test.failure.ignore=true clean package'
            }
            post {
                always {
                    junit '**/target/surefire-reports/*.xml'
                }
                success {
                    archiveArtifacts artifacts: '**/target/*.jar', followSymlinks: false
                    dir('application/target') {
                        stash includes: '*.jar', name: 'app'
                    }
                }
                failure {
                    mail bcc: '', body: 'Please review', cc: '', from: '', replyTo: '', subject: 'Build failed', to: 'david.thibau@sparks.com'
                }
            }
        }
        stage('Analyse qualité et test intégration') {
            parallel {
                stage('Tests d integration') {
                    agent any 
                    steps {
                        echo 'Tests d integration'
                        sh 'mvn -Dmaven.test.failure.ignore=true integration-test'
                    }
                    
                }
                 stage('Analyse Sonar') {
                     agent any
                     steps {
                        echo 'Analyse sonar'
                        sh 'mvn -Dmaven.test.failure.ignore=true clean verify sonar:sonar'
                     }
                    
                }
            }
            
        }
            
        stage('Sélection DATACENTER') {
            agent none
            input {
                message 'Vers quel data center voulez vous déployer ?'
                ok 'Déployer'
                parameters {
                    choice choices: ['PARIS', 'NANCY', 'STRASBOURG'], name: 'DATACENTER'
                }
            }

            steps {
                script {
                    dataCenter = "$DATACENTER"
                }
                
            }
        }
        stage('Déploiement intégration') {
            agent any
          

            steps {
                unstash 'app'
                sh "mv *.jar ${dataCenter}.jar"
                
            }
        }

     }
    
}

