apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
  labels:
    some-label: some-label-value
spec:
  containers:
    - name: jdk
      image: openjdk:11
      command:
      - cat
      tty: true